services:
  web:
    image: python-django-celery
    container_name: django-celery-app
    build:
       context: .
       dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 django_celery.wsgi:application
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app 
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: django-celery-db
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    container_name: django-celery-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  
  celery-worker:
    image: python-django-celery
    container_name: django-celery-worker
    build:
       context: .
       dockerfile: Dockerfile
    command: celery -A django_celery worker --pool=solo -l info
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
  
  celery-beat:
    image: python-django-celery
    container_name: django-celery-beat
    build:
       context: .
       dockerfile: Dockerfile
    command: celery -A django_celery beat --loglevel=info
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
  
volumes:
  postgres-data:
  redis-data:
